### ISSUE TITLE
Jenkins with Docker (docker in docker)

### ISSUE THREAD

**Issue by mewebstudio** [digitaltim-de/server-installation-docker-jenkins-portainer#3]
**Dockerfile**

```Dockerfile
FROM jenkins/jenkins:lts-jdk21

USER root

RUN apt update && curl -fsSL https://get.docker.com | sh
RUN usermod -aG docker jenkins
USER jenkins
```

**docker-compose.yml**

```yml
version: '3.8'

services:
  web:
    build: .
    container_name: jenkins-web
    restart: on-failure
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JENKINS_OPTS="--prefix=/"
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
      - jenkins-certs:/certs/client
    networks:
      - jenkins

networks:
  jenkins:
    driver: bridge

volumes:
  jenkins-data:
    driver: local
  jenkins-certs:
    driver: local
```
